# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-21 17:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModelDefaultBehavior',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('created_by',
                 django_currentuser.db.models.fields.CurrentUserField(
                     default=django_currentuser.middleware.
                     get_current_authenticated_user,
                     null=True,
                     on_delete=django.db.models.deletion.CASCADE,
                     to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestModelOnUpdate',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('updated_by',
                 django_currentuser.db.models.fields.CurrentUserField(
                     default=django_currentuser.middleware.
                     get_current_authenticated_user,
                     null=True,
                     on_delete=django.db.models.deletion.CASCADE,
                     on_update=True,
                     to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
